Ajuste de indentação

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -6,14 +6,14 @@ jobs:
     echo-hello:
         runs-on: ubuntu-latest
         steps:
-            - name: Say hello
-              run: echo "Hello, world!"
+          - name: Say hello
+            run: echo "Hello, world!"
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-        - name: Failed step
+          - name: Failed step
             run: |
-            echo "I will fail"
-            exit 1        
-        - name: Say goodbye
+              echo "I will fail"
+              exit 1        
+          - name: Say goodbye
             run: echo "Goodbye"
